application:
  jwt:
    token-count-limit: 3
    access-token-lifetime-seconds: 1200
    refresh-token-lifetime-days: 30
    secret:
      access: WatZfMdaiqiM0lg10Fi/fNzTZ4dOLzq8V+w9COMGBtQPtcype3dnI9V+9SaG9sSyCA+vWfQs3sa/yAov2OqAkQ==
      refresh: F3v7My41GWbnWC03tEjqLbVd8HRwxAkDDI4sx9qbgUQdFnjqx3S+2qKjStrXaOg/0ljPgrwu7Q3JWORri/3vpA==

server:
  port: 8081
spring:
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth"
    password: postgres
    username: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false


logging:
  file:
    name: "auth.log"
  level:
    org:
      springframework:
        web: trace

management:
  endpoints:
    web:
      exposure:
        include: "health,logfile,metrics"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: "auth.log"

