application:
  jwt:
    token-count-limit: 3
    access-token-lifetime-seconds: 3600
    refresh-token-lifetime-days: 30
    secret:
      access: WatZfMdaiqiM0lg10Fi/fNzTZ4dOLzq8V+w9COMGBtQPtcype3dnI9V+9SaG9sSyCA+vWfQs3sa/yAov2OqAkQ==
      refresh: F3v7My41GWbnWC03tEjqLbVd8HRwxAkDDI4sx9qbgUQdFnjqx3S+2qKjStrXaOg/0ljPgrwu7Q3JWORri/3vpA==

server:
  port: 8081
  address:
spring:
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth"
    password: postgres
    username: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: auth-service

logging:
  file:
    name: "auth.log"
  level:
    org:
      springframework:
        web: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: "auth.log"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
    register-with-eureka: true
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true