scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka'

    eureka_sd_configs:
      - server: http://localhost:8888/eureka

    relabel_configs: