CREATE SEQUENCE IF NOT EXISTS SQ_EMPLOYEES START WITH 1;

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    ID              INT default nextval('SQ_EMPLOYEES') PRIMARY KEY NOT NULL,
    TAB_NUM         INTEGER                                         NOT NULL,
    PASSWORD        VARCHAR(256)                                     NOT NULL,
    FIRST_NAME      VARCHAR(64)                                     NOT NULL,
    LAST_NAME       VARCHAR(128)                                    NOT NULL,
    PATRONYMIC      VARCHAR(128),
    EMAIL           VARCHAR(256),
    POSITION_NAME   VARCHAR(256),
    ACCOUNT_LOCKED  BOOLEAN                                         NOT NULL,
    ACCOUNT_ENABLED BOOLEAN                                         NOT NULL,
    CONSTRAINT UI_EMPLOYEES$TAB_NUM UNIQUE (TAB_NUM)
);

CREATE TABLE IF NOT EXISTS AUTHORITIES
(
    ID VARCHAR(32) PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_AUTHORITIES
(
    EMPLOYEE_ID  INT NOT NULL,
    AUTHORITY_ID VARCHAR(32),
    CONSTRAINT UI_EMPLOYEE_AUTHORITIES UNIQUE (EMPLOYEE_ID, AUTHORITY_ID),
    CONSTRAINT FK_EMPLOYEE_AUTHORITIES$EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES ON DELETE CASCADE,
    CONSTRAINT FK_EMPLOYEE_AUTHORITIES$AUTHORITY FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITIES ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS APPS
(
    ID   VARCHAR(16) PRIMARY KEY NOT NULL,
    NAME VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS REFRESH_TOKENS
(
   TOKEN_ID VARCHAR(36) PRIMARY KEY NOT NULL,
   REFRESH_TOKEN VARCHAR(1024) NOT NULL,
   APP_ID VARCHAR(16) NOT NULL,
   SUBJECT VARCHAR(128) NOT NULL,
   EXPIRATION TIMESTAMP(6)  NOT NULL,
   CONSTRAINT FK_REFRESH_TOKENS$APP FOREIGN KEY (APP_ID) REFERENCES APPS ON DELETE CASCADE
);

CREATE INDEX IDX_REFRESH_TOKENS$APP_SUBJ ON REFRESH_TOKENS(APP_ID, SUBJECT);
CREATE INDEX IDX_REFRESH_TOKENS$EXPIRATION ON REFRESH_TOKENS(EXPIRATION);


