spring:
  application:
    name: eureka-server

server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: "sd.log"

logging:
  file:
    name: "sd.log"